2021-09-15 20:41:58,444 ERROR frappe New Exception collected with id: 2021-09-15 20:41:58.178386-127.0.0.1-2eb
Site: library.test
Form Dict: {'doctype': 'Library Membership', 'with_parent': '1', 'cached_timestamp': '', 'cmd': 'frappe.desk.form.load.getdoctype'}
2021-09-15 20:42:36,784 ERROR frappe New Exception collected with id: 2021-09-15 20:42:36.735093-127.0.0.1-046
Site: library.test
Form Dict: {'doctype': 'Library Membership', 'with_parent': '1', 'cached_timestamp': '', 'cmd': 'frappe.desk.form.load.getdoctype'}
2021-09-15 20:48:52,505 ERROR frappe New Exception collected with id: 2021-09-15 20:48:52.029290-127.0.0.1-ad0
Site: library.test
Form Dict: {'doc': '{"name":"LMS000002","owner":"Administrator","creation":"2021-09-15 20:46:06.870412","modified":"2021-09-15 20:46:06.870412","modified_by":"Administrator","idx":0,"docstatus":0,"library_member":"LM0002","from_date":"2021-09-01","to_date":"2021-09-02","paid":0,"doctype":"Library Membership"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-09-16 04:35:26,074 ERROR frappe Could not take error snapshot: characters_written
Site: library.test
Form Dict: {'items': '["/assets/frappe/dist/js/build_events.bundle.HQFRKT43.js"]', 'cmd': 'frappe.client.get_js'}
Traceback (most recent call last):
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1204, in call
    return fn(*args, **newargs)
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/client.py", line 330, in get_js
    with open(contentpath, "r") as srcfile:
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/dist/js/build_events.bundle.HQFRKT43.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/Users/greggy/thanos/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
